# pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Hooks are scripts or rules that are triggered at certain point to automate tasks, check issues in code.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # checks for and removes any trailing whitespace at the end of lines in the          code.
    -   id: trailing-whitespace
    # ensures that each file has a newline at the end.
    -   id: end-of-file-fixer
    # validates YAML files for syntax errors and potential issues. 
    -   id: check-yaml
    # checks for large files that are being added to the repository.
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    # uses the isort tool to automatically sort and organize Python import               statements in the code.
      - id: isort
      - name: isort(python)

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    # uses the yapf tool to format Python code according to a consistent style.
    # Uses default settings or we can configure inside .style.yapf file.
      - id: yapf # (Yet Another Python Formatter)
        additional_dependencies: [ toml ]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    # uses the flake8 tool, which is a linting tool for Python.
    # It checks your code for various issues, including syntax errors, style             violations, and potential bugs.
      - id: flake8
        additional_dependencies:
        # Additional checks for common programming mistakes.
        # E.g: use of == or != with True or False or None. It encourages to use is                or is not.
          - flake8-bugbear
        # Checks for the use of Python built-in functions
        # E.g: Use of map, filter, and lambda instead of list comprehensions,
        #      Use of open without a with statement:
          - flake8-builtins
        # Checks for violations of PEP 263 (Source Code Encoding).
          - flake8-coding
        # Enforces a consistent order of import statements.
          - flake8-import-order
        # Polyfill for supporting plugins requiring a newer flake8 version.
          - flake8-polyfill
        # Enforces a consistent use of single or double quotes like single quotes            for single line and
        # double for multiple lines
          - flake8-quotes
          
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format